version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "smileybane.net"
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo pwd
      - echo Installing source NPM dependencies...
      - pushd family/src/main/client/family
      - npm install
      - npm install -g @angular/cli
      - popd
  build:
    commands:
      - echo Build started on `date`
      - pushd family/src/main/client/family
      - ng build --env=${BUILD_ENV}
      - popd
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes