version: 0.2
environment_variables:
  plaintext:
    S3_BUCKET: "smileybane.net"
    BUILD_ENV: "prod"
    CLIENT: "src/main/client/family"
    HOME: "../../../.."
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - echo CLIENT=${CLIENT}
      - cd ${CLIENT}
      - pwd
      - npm install
      - npm install -g @angular/cli
      - cd ${HOME}
  build:
    commands:
      - echo Build started on `date`
      - echo CLIENT=${CLIENT}
      - cd ${CLIENT}
      - pwd
      - ng build
      - cd ${HOME}
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes